# Generated by Django 3.1.2 on 2022-08-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
